[2022-11-07T04:50:29.071+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-11-06T00:00:00+00:00 [queued]>
[2022-11-07T04:50:29.076+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.choose_best_model scheduled__2022-11-06T00:00:00+00:00 [queued]>
[2022-11-07T04:50:29.076+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-07T04:50:29.076+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-07T04:50:29.076+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-07T04:50:29.084+0000] {taskinstance.py:1383} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2022-11-06 00:00:00+00:00
[2022-11-07T04:50:29.087+0000] {standard_task_runner.py:55} INFO - Started process 254 to run task
[2022-11-07T04:50:29.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'scheduled__2022-11-06T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3rq2apn7']
[2022-11-07T04:50:29.089+0000] {standard_task_runner.py:83} INFO - Job 163: Subtask choose_best_model
[2022-11-07T04:50:29.123+0000] {task_command.py:376} INFO - Running <TaskInstance: my_dag.choose_best_model scheduled__2022-11-06T00:00:00+00:00 [running]> on host 65bebd3e66a2
[2022-11-07T04:50:29.159+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=choose_best_model
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-06T00:00:00+00:00
[2022-11-07T04:50:29.159+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 211, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 12, in _choose_best_model
    accuracies = ti.xcom.pull(task_ids=[
AttributeError: 'TaskInstance' object has no attribute 'xcom'
[2022-11-07T04:50:29.164+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=my_dag, task_id=choose_best_model, execution_date=20221106T000000, start_date=20221107T045029, end_date=20221107T045029
[2022-11-07T04:50:29.170+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 163 for task choose_best_model ('TaskInstance' object has no attribute 'xcom'; 254)
[2022-11-07T04:50:29.182+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-07T04:50:29.200+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
